
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Entered the 'pre_build' phase..."
      - apt-get install -y cmake
      - echo `gcc --version`
  build:
    commands:
      - echo "Entered the 'build' phase..."
      - mkdir bin
      - cd bin
      - cmake ../
